import Head from "next/head";
import { GetStaticProps, NextPage } from "next";
import { IDrinkProp } from "@/interfaces/IDrink";
import DrinkList from "@/components/home/DrinkList/DrinkList";

const Home: NextPage<IDrinkProp> = ({ drinks }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DrinkList drinks={drinks} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  const alcoholicDrinks = `${process.env.API_URL}/filter.php?a=Alcoholic`;
  const res = await fetch(alcoholicDrinks);
  const data = await res.json();
  const drinks = data.drinks;

  return {
    props: {
      drinks: drinks,
    },
  };
};

export default Home;
